#!/bin/bash

# Define color variables
green=$(tput setaf 2)
reset=$(tput sgr0)

# get processor information
processor_name=$(grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1)
processor_count=$(grep -ioP 'processor\t:' /proc/cpuinfo | wc -l)

# Function to detect GPU
detect_gpu() {
    if command -v nvidia-smi &>/dev/null; then
        system_gpu=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n 1)
        model_number=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader | head -n 1)
    elif lspci | grep -i AMD &>/dev/null; then
        system_gpu=$(lspci | grep -i AMD | grep -oP "(?<=\[).+?(?=\])" | head -n 1)
        model_number=$(lspci | grep -i AMD | grep -i VGA | cut -d ' ' -f12- | head -1)
    else
        manufacturer="Unknown"
        system_gpu="${yellow}No compatible GPU found${reset}"
        model_number="N/A"
    fi
}
detect_gpu

# Get process information
process=$(ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }')
process_all=$(echo "$process" | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
process_root=$(echo "$process" | grep root | awk {'print $2'})
process_user=$(echo "$process" | grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')

# get load averages
IFS=" " read load1 load5 load15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')

# get free memory
IFS=" " read used avail total <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})

# get swap usage
IFS=" " read swap_used swap_total <<<$(free -htm | grep "Swap" | awk {'print $3,$2'})

echo -e "${reset}  Distro......: ${reset}$(cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g')
${reset}  Kernel......: ${reset}$(uname -sr)
${reset}  Uptime......: ${reset}$(uptime -p)
${reset}  CPU.........: ${reset}$processor_name (${green}$processor_count${reset} vCPU)
${reset}  GPU.........: ${reset}$system_gpu $model_number
${reset}  Processes...: ${reset}${green}$process_root${reset} (root), ${green}$process_user${reset} (user), ${green}$process_all${reset} (total)
${reset}  Load........: ${green}$load1${reset} (1m), ${green}$load5${reset} (5m), ${green}$load15${reset} (15m)
${reset}  RAM.USAGE...: ${green}$used${reset} used, ${green}$avail${reset} avail, ${green}$total${reset}
${reset}  SWAP.USAGE..: ${green}$swap_used${reset} used, ${green}$swap_total${reset} total"
