#!/bin/bash

# Function to detect GPU
detect_gpu() {
    if command -v nvidia-smi &>/dev/null; then
        SYSTEM_GPU=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n 1)
        MODEL_NUMBER=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader | head -n 1)
    elif lspci | grep -i AMD &>/dev/null; then
        SYSTEM_GPU=$(lspci | grep -i AMD | grep -oP "(?<=\[).+?(?=\])" | head -n 1)
        MODEL_NUMBER=$(lspci | grep -i AMD | grep -i VGA | cut -d ' ' -f12- | head -1)
    else
        MANUFACTURER="Unknown"
        SYSTEM_GPU="No compatible GPU found"
        MODEL_NUMBER="N/A"
    fi
}

# Call the function to detect GPU
detect_gpu

W="\e[0;39m"
G="\e[1;32m"

# get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')
# get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})
# get processes
PROCESS=$(ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }')
PROCESS_ALL=$(echo "$PROCESS" | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
PROCESS_ROOT=$(echo "$PROCESS" | grep root | awk {'print $2'})
PROCESS_USER=$(echo "$PROCESS" | grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }')
# get processors
PROCESSOR_NAME=$(grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1)
PROCESSOR_COUNT=$(grep -ioP 'processor\t:' /proc/cpuinfo | wc -l)

echo -e "
${W}SYSTEM INFO:
$W  Distro......: $W$(cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g')
$W  Kernel......: $W$(uname -sr)
$W  Uptime......: $W$(uptime -p)
$W  Load........: $G$LOAD1$W (1m), $G$LOAD5$W (5m), $G$LOAD15$W (15m)
$W  Processes...:$W $G$PROCESS_ROOT$W (root), $G$PROCESS_USER$W (user), $G$PROCESS_ALL$W (total)
$W  CPU.........: $W$PROCESSOR_NAME ($G$PROCESSOR_COUNT$W vCPU)
$W  GPU.........: $SYSTEM_GPU $MODEL_NUMBER
$W  RAM.USAGE...: $G$USED$W used, $G$AVAIL$W avail, $G$TOTAL$W total$W"
