#!/bin/bash

# Set colors for better visibility
green=$(tput setaf 2)
yellow=$(tput setaf 3)
red=$(tput setaf 1)
reset=$(tput sgr0) # No Color

# Function to check disk status and display appropriate color
check_disk_status() {
    disk="$1"
    status=$(sudo smartctl -H $disk | awk '/test result/ {print $NF}')

    if [ "$status" == "PASSED" ]; then
        echo -e "${green}OK${reset}"
    elif [ "$status" == "FAILED!" ]; then
        echo -e "${red}FAIL${reset}"
    else
        echo -e "${yellow}WARN${reset}"
    fi
}

# Display disk information and status with aligned columns in groups of 4
echo "" # blank
echo -e "Disk Health [${green}OK${reset}/${yellow}WARN${reset}/${red}FAIL${reset}]"
count=0
for disk in $(lsblk -o NAME -nl | grep -E '^sd[a-z]$|^nvme[0-9]n[0-9]$|^mmcblk[0-9]$|^xvd[a-z]$'); do
    status=$(check_disk_status "/dev/$disk")
    printf " %-11s%s" "$disk" "$status"
    ((count++))

    # Add a newline after every disk except the last one
    if [ $count -lt 4 ]; then
        echo -n "   "
    else
        echo
        count=0
    fi
done

# Add a newline if the last group doesn't have 4 disks
if [ $count -ne 0 ]; then
    echo
fi
