#!/bin/bash

# set column width
COLUMNS=3

# Set colors for better visibility
green='\033[0;32m'
red='\033[0;31m'
reset='\033[0m'

## EDIT YOUR SERVICES HERE
services=("nginx" "smbd" "lxd" "ufw")

# sort services
IFS=$'\n' services=($(sort <<<"${services[*]}"))
unset IFS

service_status=()
# get status of all services
for service in "${services[@]}"; do
    service_status+=($(systemctl is-active "$service"))
done

out=""
for i in ${!services[@]}; do
    # color green if service is active, else red
    if [[ "${service_status[$i]}" == "active" ]]; then
        out+="${services[$i]}:,${green}${service_status[$i]}${reset},"
    else
        out+="${services[$i]}:,${red}${service_status[$i]}${reset},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done
out+="\n"

printf "\nIMPORTANT SERVICES:\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
