#!/usr/bin/env bash

# Set colors for better visibility
green='\033[0;32m'
red='\033[0;31m'
reset='\033[0m'

columns=2
filter='nothing'  # excluded containers separated by |

mapfile -t containers < <(docker ps -a --format "{{.Names}} {{.Status}}" | awk '!/^('${filter}')/{print $1,$2}' | sort)

out=''
for i in "${!containers[@]}"; do
    IFS=" " read name status <<< "${containers[$i]}"
    # Use color variables for circle (o) and x
    if [[ "${status}" == 'Up' ]]; then
        status="${green}o${reset}"
    else
        status="${red}x${reset}"
    fi
    out+="${status}|${name}|"
    (( $(( (i+1) % columns )) == 0 )) && out+='\n'
done

if [[ -z "${out}" ]]; then
    out='none'
fi
out+='\n'

echo
echo 'DOCKER CONTAINERS:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'
