#!/usr/bin/env bash

# PULLED THIS FROM GITHUB
# https://github.com/bcyran/fancy-motd
# RIPPED OUT THE UPDATE MODULE AND
# REARRANGED IT'S GUTS

set -eu

# Colors
blue="${blue:-\e[34m}"    # Accent (blue)
green="${green:-\e[1;32m}"  # Ok (bright green)
yellow="${yellow:-\e[33m}"  # Warning (yellow)
red="${red:-\e[31m}"        # Error (red)
reset="${reset:-\e[0m}"     # None (reset)

print_color() {
    local out=""
    if [[ "$2" -lt "$3" ]]; then
        out+="${green}"
    elif [[ "$2" -ge "$3" && "$2" -lt "$4" ]]; then
        out+="${yellow}"
    else
        out+="${red}"
    fi
    out+="$1${reset}"
    echo "$out"
}

print_columns() {
    [ -z "$2" ] && return
    echo -e ""
    paste <(echo -e "${blue}$1${1:+:}${reset}") <(echo -e "$2")
}

if type checkupdates >/dev/null 2>&1; then
    updates=$(checkupdates 2> /dev/null | wc -l )
    if type yay >/dev/null 2>&1; then
        updates_aur=$(yay -Qum 2> /dev/null | wc -l)
        updates=$((updates + updates_aur))
    fi
elif type dnf >/dev/null 2>&1; then
    updates=$(dnf check-update --quiet | grep -v "^$" | wc -l)
elif type apt >/dev/null 2>&1; then
    updates=$(apt list --upgradable 2>/dev/null | grep upgradable | wc -l)
else
    updates="N/A"
fi

text="$(print_color "$updates available" "$updates" 1 50)"

print_columns "\e[0;37mUPDATES AVAILABLE" "$text"
